config/routes.rb
Rails.application.routes.draw do
  resources :characters do
    resources :stats
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :stats
  validates :name, presence: true,
            length: { minimum: 2 }
  #validates :kurzbeschreibung, presence: true,
   #         length: {minimum: 3}
end

app/models/stat.rb
class Stat < ApplicationRecord
  belongs_to :character
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def new
    @character = Character.new
  end

  def edit
    @character = Character.find(params[:id])
  end

  def index
    @characters = Character.all
  end

  def show
    @character= Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])

    if @character.update(character_params)
      redirect_to @character
    else
      render 'edit'
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy;
    redirect_to characters_path
  end

  def create
    @character = Character.new(character_params)

    if(@character.save)
      redirect_to @character
    else
      render 'new'
    end
  end

  private
    def character_params
      params.require(:character).permit(:name, :kurzbeschreibung)
    end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

  def create
    @character = Character.find(params[:character_id])
    @stat = @character.stats.create(stat_params)
    redirect_to character_path(@character)
  end

  def edit
    @character = Character.find(params[:character_id])
    @stat = Stat.find(params[:id])
  end

  def update
    @character = Character.find(params[:character_id])
    @stat = @character.stats.find(params[:id])

    if @stat.update(stat_params)
      redirect_to @character.stat
    else
      render 'edit'
    end
  end


  private
  def stat_params
    params.require(:stat).permit(:strength, :agility, :stamina)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/characters/_form.html.erb
<%= form_for @character do |f| %>

    <% if @character.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@character.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @character.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :kurzbeschreibung %><br>
      <%= f.text_area :kurzbeschreibung %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>
<%= link_to 'New Character', new_character_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Kurzbeschreibung</th>
  </tr>

  <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.kurzbeschreibung %></td>
        <td><%= link_to 'Show', character_path(character) %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character_path(character),
                method: :delete,
                data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

app/views/characters/new.html.erb
<h1>New Character!</h1>
<%= form_for :character, url: characters_path  do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :kurzbeschreibung %><br>
      <%= f.text_area :kurzbeschreibung %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>
<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Kurzbeschreibung:</strong>
  <%= @character.kurzbeschreibung %>
</p>

<h2>Stats</h2>
<%= render @character.stats %>

<h2>Add Stats</h2>
<%= render 'stats/form' %>


<%= link_to 'Edit', edit_character_path(@character)%>
<%= link_to 'Back', characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DnDManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stats/_form.html.erb
<%= form_for([@character, @character.stats.build]) do |f| %>
    <p>
      <%= f.label :strength %><br>
      <%= f.text_field :strength %>
    </p>
    <p>
      <%= f.label :agility %><br>
      <%= f.text_field :agility %>
    </p>
    <p>
      <%= f.label :stamina %><br>
      <%= f.text_field :stamina %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/stats/_stat.html.erb
<p>
  <strong>Strength:</strong>
  <%= stat.strength %>
</p>

<p>
  <strong>Agility:</strong>
  <%= stat.agility %>
</p>

<p>
  <strong>Stamina:</strong>
  <%= stat.stamina %>
</p>

<p>
<td><%= link_to 'Edit', edit_character_stat_path(stat) %></td>
</p>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'DnDManager', controller: 'characters' %>